version: "3"

services:
  db:
    image: mysql
    container_name: mysql_57
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
  metabase:
    image: metabase/metabase
    container_name: metabase
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    ports: 
      - "3000:3000"
    volumes:
      - data:/metabase-data/metabase.db
      
networks:
  rede_projeto:
    external: true

volumes:
    data:
      driver: local
    mysql_volume:
      driver: local