version: "3"

services:
  database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  metabase:
    image: metabase/metabase
    container_name: metabase
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    ports: 
      - "3000:3000"
    volumes:
      - data:/metabase-data/metabase.db
      
networks:
  rede_projeto:
    external: true

volumes:
    data:
      driver: local
    postgres_volume:
      driver: local